@startuml

class 客户端1
class 客户端2
class 客户端3

class 子系统1
class 子系统2
class 子系统3


客户端1 ..> 子系统1
客户端1 ..> 子系统2
客户端1 ..> 子系统3

客户端2 ..> 子系统1
客户端2 ..> 子系统2
客户端2 ..> 子系统3

客户端3 ..> 子系统1
客户端3 ..> 子系统2
客户端3 ..> 子系统3


@enduml