@startuml

class 产品111
class 产品112
class 产品121
class 产品122
class 产品211
class 产品212
class 产品221
class 产品222

class 具体维度1变化1
class 具体维度1变化2
class 具体维度2变化1
class 具体维度2变化2
class 具体维度3变化1
class 具体维度3变化2

产品111 *-u-> 具体维度1变化1
产品111 *-u-> 具体维度2变化1
产品111 *-u-> 具体维度3变化1

产品112 *-u-> 具体维度1变化1
产品112 *-u-> 具体维度2变化1
产品112 *-u-> 具体维度3变化2

产品121 *-u-> 具体维度1变化1
产品121 *-u-> 具体维度2变化2
产品121 *-u-> 具体维度3变化1

产品122 *-u-> 具体维度1变化1
产品122 *-u-> 具体维度2变化2
产品122 *-u-> 具体维度3变化2

产品211 *-u-> 具体维度1变化2
产品211 *-u-> 具体维度2变化1
产品211 *-u-> 具体维度3变化1

产品212 *-u-> 具体维度1变化2
产品212 *-u-> 具体维度2变化1
产品212 *-u-> 具体维度3变化2

产品221 *-u-> 具体维度1变化2
产品221 *-u-> 具体维度2变化2
产品221 *-u-> 具体维度3变化1

产品222 *-u-> 具体维度1变化2
产品222 *-u-> 具体维度2变化2
产品222 *-u-> 具体维度3变化2

@enduml