@startuml

class 桥接对象{
    抽象维度1
    抽象维度2
    抽象维度3
}
interface 抽象维度1
interface 抽象维度2
interface 抽象维度3

class 具体维度1变化1
class 具体维度1变化2
class 具体维度2变化1
class 具体维度2变化2
class 具体维度3变化1
class 具体维度3变化2

桥接对象 *-d-> 抽象维度1
桥接对象 *-d-> 抽象维度2
桥接对象 *-d-> 抽象维度3

具体维度1变化1 -u.|> 抽象维度1
具体维度1变化2 -u.|> 抽象维度1
具体维度2变化1 -u.|> 抽象维度2
具体维度2变化2 -u.|> 抽象维度2
具体维度3变化1 -u.|> 抽象维度3
具体维度3变化2 -u.|> 抽象维度3
@enduml