@startuml

interface 抽象工厂{
    抽象产品等级1: 创建抽象产品等级1()
    抽象产品等级2: 创建抽象产品等级2()
}
class 具体产品族工厂

interface 抽象产品等级1
interface 抽象产品等级2

class 具体产品等级1
class 具体产品等级2

具体产品等级1 -u.|> 抽象产品等级1
具体产品等级2 -u.|> 抽象产品等级2
具体产品族工厂 -u.|> 抽象工厂

具体产品族工厂 .> 具体产品等级1 :创建
具体产品族工厂 .> 具体产品等级2 :创建
@enduml
