@startuml

interface 抽象组件角色{
    + 操作()
}
class 具体组件角色{
    + 操作()
}
abstract class 抽象装饰者角色{
    # 抽象组件角色
    # 抽象装饰者角色(抽象组件角色) : 构造器
    + 操作()
    + 增加的操作()
}
class 具体装饰者角色{
    + 具体装饰者角色(抽象组件角色) : 构造器
    + 操作()
    + 增加的操作()
}

具体组件角色 -u..|> 抽象组件角色
具体装饰者角色 -u.|> 抽象装饰者角色
抽象装饰者角色 o-u-|> 抽象组件角色 : 包含
抽象装饰者角色 ..|> 抽象组件角色
@enduml