@startuml
class Client

class Action1
class Action2
class Action3

class Service1
class Service2
class Service3

class Dao1
class Dao2
class Dao3

Client --> Action1
Client --> Action2
Client --> Action3

Action1 --> Service1
Action1 --> Service2
Action1 --> Service3
Action2 --> Service1
Action2 --> Service2
Action2 --> Service3
Action3 --> Service1
Action3 --> Service2
Action3 --> Service3

Service1 --> Dao1
Service1 --> Dao2
Service1 --> Dao3
Service2 --> Dao1
Service2 --> Dao2
Service2 --> Dao3
Service3 --> Dao1
Service3 --> Dao2
Service3 --> Dao3



@enduml